Header
js-tasks-ru/htmlcss-20240216_nastya-burdenkova pull request #17
Opened 2024-03-20 20:25 UTC by kamille57

2024-03-20 20:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-20 22:16 UTC, GSemikozov requested changes

2024-03-20 22:16 UTC, GSemikozov commented on components/header/header.css
> +.header-container {
просто header?

2024-03-21 09:33 UTC, kamille57 commented on components/header/header.css
> +.header-container {
не понимаю как мне избавиться от header-container, тк сам header без стилей, но нужен семантически, просто container центрует страницу, а header-container собирает контент страницы в нужном порядке

2024-03-21 12:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-22 18:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-22 18:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-22 18:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-22 18:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-24 14:49 UTC, GSemikozov commented on components/header/header.css
> +.header-container {
если это элемент хедера, значит header__inner

2024-03-24 20:51 UTC, closed without merging