Task 4  histogram solution
js-tasks-ru/htmlcss-20240216_nastya-burdenkova pull request #6
Opened 2024-03-06 19:17 UTC by kamille57

2024-03-06 19:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 09:27 UTC, GSemikozov requested changes

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту удаляем

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-radius: 10px;
8

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__titles-container {
.histogram__titles

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__title-link {
.histogram__link

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__title-total {
.histogram__total

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item-container {
.histogram__chart

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item-container {
margin-top: 39px

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-columns: repeat(30, 9px);
грид нам здесь не нужен, поскольку количество колонок может быть разным

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    grid-auto-rows: 50px;
и тогда мы просто зафиксируем высоту в 50px

2024-03-12 09:27 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-height: 11px;
а высоту айтемов будем задавать в процентах. И минимальную высоту ставить не надо - это обман пользователя) все данные для таких графиков обычно приходят с сервера, и если значение null - то лучше показать 0, а не 22% :)

2024-03-12 21:42 UTC, GSemikozov requested changes

2024-03-12 21:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 22%;
по умолчанию не надо никаких значений) ну, разве что 0.

2024-03-13 07:50 UTC, kamille57 commented on 04-lection2/01-histogram/histogram.css
> +    height: 22%;
а теперь там пустота в этих местах. это ничего? или надо добавить модификатор туда на 22% еще?

2024-03-14 10:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 22%;
да, конечно, если высоту определяем через модификаторы - тогда да (.histogram__item_small etc)

2024-03-14 10:38 UTC, GSemikozov requested changes

2024-03-14 10:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis: 9px

2024-03-18 13:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-18 15:45 UTC, GSemikozov submitted a review, later dismissed

2024-03-18 15:45 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-18 15:45 UTC, GSemikozov approved these changes

2024-03-18 15:46 UTC, merged