add solution for skeleton
js-tasks-ru/htmlcss-20240216_nastya-burdenkova pull request #8
Opened 2024-03-07 07:40 UTC by kamille57

2024-03-07 07:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 09:30 UTC, GSemikozov requested changes

2024-03-12 09:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
ширину и высоту удаляем

2024-03-12 09:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    grid-template-rows: repeat(3, max-content);
вроде 2? 3 кажется лишним

2024-03-12 09:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    justify-content: space-between;
лишнее

2024-03-12 09:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header {
отсюда и ниже - это все один и тот же элемент, .skeelton__line, отличаются лишь шириной (управляем через модификатор)

2024-03-12 09:30 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header {
и тогда не надо дублировать одни и те же стили

2024-03-12 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 19:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 19:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 19:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 21:43 UTC, GSemikozov requested changes

2024-03-12 21:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину у модификаторов - в процентах

2024-03-13 07:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-13 07:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-13 08:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 10:36 UTC, GSemikozov approved these changes

2024-03-14 10:36 UTC, merged