add solution for avatar
js-tasks-ru/htmlcss-20240216_nastya-burdenkova pull request #9
Opened 2024-03-18 15:07 UTC by kamille57

2024-03-18 15:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-18 15:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 15:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 15:44 UTC, GSemikozov requested changes

2024-03-18 15:44 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    object-fit: cover;
а еще - `height: 100%; width: 100%`

2024-03-20 22:07 UTC, GSemikozov approved these changes

2024-03-20 22:07 UTC, merged